add padding on iOS
SatorNetwork/sator-flutter-client pull request #100
Opened 2021-09-14 17:36 UTC by mbortsov

2021-09-14 23:48 UTC, MichaelBoostyLabs requested changes

2021-09-14 23:48 UTC, MichaelBoostyLabs commented on lib/controller/login_controller.dart
> +  late final double bottomPadding;
move from controller to page - it for ui only

2021-09-17 11:43 UTC, mbortsov commented on lib/controller/login_controller.dart
> +  late final double bottomPadding;
done

2021-09-17 12:53 UTC, MichaelBoostyLabs approved these changes

2021-09-17 14:33 UTC, merged