Sat-297 New bottom navbar
SatorNetwork/sator-flutter-client pull request #53
Opened 2021-07-27 22:20 UTC by MichaelBoostyLabs

https://nftprojectsboosty.atlassian.net/browse/SAT-297 New bottom navbar
https://nftprojectsboosty.atlassian.net/browse/SAT-210 Misprint in Logout dialog
https://nftprojectsboosty.atlassian.net/browse/SAT-215 Typo in Reset password screen

2021-07-28 05:04 UTC, dmitrymomot requested changes
pls make navbar animation more quickly

2021-07-28 11:27 UTC, MichaelBoostyLabs commented
> pls make navbar animation more quickly

done

2021-07-28 20:04 UTC, dmitrymomot requested changes
could you pls set icons from Figma in navbar "as is"
and link navbar items to correct screens

2021-07-30 04:11 UTC, dmitrymomot approved these changes

2021-07-30 04:11 UTC, merged