SAT-409 Show current email
SatorNetwork/sator-flutter-client pull request #98
Opened 2021-09-13 18:12 UTC by mbortsov

2021-09-14 23:44 UTC, MichaelBoostyLabs requested changes

2021-09-14 23:44 UTC, MichaelBoostyLabs commented on lib/translation/en.dart
> +  'txt_verification_text_2': ' or use the link from your inbox',
use string with parameters instead 2 parts

2021-09-14 23:44 UTC, MichaelBoostyLabs commented on lib/ui/page_widget/email_verification_page.dart
> +                  Row(
use simple Text with formatted string

2021-09-17 11:39 UTC, mbortsov commented on lib/translation/en.dart
> +  'txt_verification_text_2': ' or use the link from your inbox',
done

2021-09-17 11:39 UTC, mbortsov commented on lib/ui/page_widget/email_verification_page.dart
> +                  Row(
done

2021-09-17 12:52 UTC, MichaelBoostyLabs approved these changes

2021-09-17 14:29 UTC, merged